### ISSUE TITLE
Error performing action

### ISSUE THREAD

**Issue by leandromoreirati** [rauhmaru/rocketchat-zabbix#1]
Dear good afternoon
I followed his documentation to integrate zabbix with the rocket chat, but at the time he performs the action he is returning the error below:

![image](https://user-images.githubusercontent.com/30784301/57884653-85ffa400-77ff-11e9-93ee-da7ec4b5d232.png)

Can you please give me a hint how to solve.

Att.

**Comment by rauhmaru** [comment]
Leandro, qual a versão do seu Zabbix?

**Comment by leandromoreirati** [comment]
Boa noite Raul, como vai

Estou usando a versao 4.0.7.

Att.

**Comment by rauhmaru** [comment]
Leandro, vou subir um lab pra simular com essa versão, e darei um retorno.
Como estou em um ambiente legado, uso a versão 2.4.5, mas atualizarei para mais recentes. Creio que o erro pode estar na ordem dos argumentos do script python.

**Comment by leandromoreirati** [comment]
Raul,

Muito obrigado pela atenção, fico no aguardo.

Att.


Em seg, 20 de mai de 2019 15:41, Raul Libório <notifications@github.com>
escreveu:

**Comment by AlKosmos** [comment]
I can confirm. Unfortunately, I am getting the same issue without media script parameters in Zabbix 4.0.7.
```
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/rocketchat.py", line 7, in <module>
url = sys.argv[1]
IndexError: list index out of range
```
If i add the script parameters for Media type manually:
```
{ALERT.SENDTO}
{ALERT.SUBJECT}
{ALERT.MESSAGE} 
```
Action has the status "Sent", but I am not getting anything in RocketChat.

**Comment by leandromoreirati** [comment]
Hi, AlKosmos!

I make same test, inclur the variables:

{ALERT.SENDTO}
{ALERT.SUBJECT}
{ALERT.MESSAGE} 

In the media configuration, it return "Send Menssage", but not sending.

At.

**Comment by petqa** [comment]
good day, same issue on 4.2.3, any fixes?

**Comment by rauhmaru** [comment]
Hi, sorry for delay.
1. The python script was missing a line at the end:


```
#!/usr/bin/python

import sys
import requests
import json

url     = sys.argv[1]
subject = sys.argv[2]
body    = sys.argv[3]

r = requests.post(url, body)
```

2. Config with this parameters:

![Image of Config](http://susepaste.org/images/54990174.PNG)

And will works.

I apologize to everyone for their inattention.

**Comment by petqa** [comment]
thank you, alerts working now, but now i'm not getting images from alerts

`No permissions to referred object or it does not exist`

**Comment by rauhmaru** [comment]
As images are brought from zabbix via the link, then, in order to have access, you must be logged in.

Another point is that the rocketchat should be able to reach zabbix so that the images can be viewed.

**Comment by petqa** [comment]
Can you please describe in more detail how I should make an entry in zabbix, by editing the source python script?

**Comment by rauhmaru** [comment]
@petqa, I do not understand what you want.
You refer a the alertscript in the zabbix?
Only the last line in the script was missing, sending the information to the chat.
