### ISSUE TITLE
Note: To view the graphs, you need to be logged in to Zabbix.

### ISSUE THREAD

**Issue by masoudmirzajani** [rauhmaru/rocketchat-zabbix#3]
Hi,
How can logged in to zabbix, Ican not view graph on notification.
Thanks

**Comment by ewerton-silva00** [comment]
I can't view the graphics even though I am logged in to Zabbix.

![Screenshot from 2019-09-12 11-51-32](https://user-images.githubusercontent.com/22784708/64794956-b5c37c00-d553-11e9-88c5-10b08ba97ac5.png)

**Comment by rauhmaru** [comment]
> I can't view the graphics even though I am logged in to Zabbix.
> 
> ![Screenshot from 2019-09-12 11-51-32](https://user-images.githubusercontent.com/22784708/64794956-b5c37c00-d553-11e9-88c5-10b08ba97ac5.png)

Ewerton, please, show me your recovery message.

**Comment by rauhmaru** [comment]
> notification

Hi, the cookies are enabled?

**Comment by ewerton-silva00** [comment]
> > I can't view the graphics even though I am logged in to Zabbix.
> > ![Screenshot from 2019-09-12 11-51-32](https://user-images.githubusercontent.com/22784708/64794956-b5c37c00-d553-11e9-88c5-10b08ba97ac5.png)
> 
> Ewerton, please, show me your recovery message.

Recovery Message:

{
  "text": ":white_check_mark: *{TRIGGER.NAME} ({ITEM.VALUE1})*",
  "attachments": [
    {
      "color": "#00FF00",
      "title": "[RESOLVIDO] {HOST.NAME}  ({HOST.CONN})",
      "title_link": "https://zabbix.example.com/tr_events.php?triggerid={TRIGGER.ID}&eventid={EVENT.ID}",
      "text": "Verified in {TIME}, at {EVENT.DATE}",
      "image_url": "https://zabbix.example.com/zabbix/chart3.php?&width=500&height=150&period=3600&name={HOST.NAME}: {TRIGGER.NAME}&legend=1&items[0][itemid]={ITEM.ID}&items[0][drawtype]=5&items[0][color]=00ff00"
    }
  ]
}

**Comment by ewerton-silva00** [comment]
> > > I can't view the graphics even though I am logged in to Zabbix.
> > > ![Screenshot from 2019-09-12 11-51-32](https://user-images.githubusercontent.com/22784708/64794956-b5c37c00-d553-11e9-88c5-10b08ba97ac5.png)
> > 
> > 
> > Ewerton, please, show me your recovery message.
> 
> Recovery Message:
> 
> {
> "text": "white_check_mark _{TRIGGER.NAME} ({ITEM.VALUE1})_",
> "attachments": [
> {
> "color": "#00FF00",
> "title": "[RESOLVIDO] {HOST.NAME} ({HOST.CONN})",
> "title_link": "https://zabbix.example.com/tr_events.php?triggerid={TRIGGER.ID}&eventid={EVENT.ID}",
> "text": "Verified in {TIME}, at {EVENT.DATE}",
> "image_url": "https://zabbix.example.com/zabbix/chart3.php?&width=500&height=150&period=3600&name={HOST.NAME}: {TRIGGER.NAME}&legend=1&items[0][itemid]={ITEM.ID}&items[0][drawtype]=5&items[0][color]=00ff00"
> }
> ]
> }

The URL in title_link works if I paste it directly into the browser.

**Comment by rauhmaru** [comment]
And the image_url works too if you paste into browser?

**Comment by rauhmaru** [comment]
@ewerton-silva00, you has edited the image_url with your zabbix url?

**Comment by ewerton-silva00** [comment]
> And the image_url works too if you paste into browser?

Yes, it works.

**Comment by rauhmaru** [comment]
Whats your zabbix version?
Please, go to Reports > Action log and see the image_url is functional

**Comment by ewerton-silva00** [comment]
> you has edited the image_url with your zabbix url?



> @ewerton-silva00, you has edited the image_url with your zabbix url?

Yes, I entered the address of my zabbix.

**Comment by ewerton-silva00** [comment]
> Whats your zabbix version?
> Please, go to Reports > Action log and see the image_url is functional

Zabbix version 4.0.7.
In Action Log, if I copy and paste the image_url in the browser works, but in Rocketchat it doesn't work.

**Comment by rauhmaru** [comment]
Well... I can't imagine what's happening with you configuration :(

**Comment by Welkin-cf** [comment]
> Well... I can't imagine what's happening with you configuration :(

{TRIGGER.NAME} may cause spaces in the link, sometimes the browser does not recognize the url correctly and can't access the image

**Comment by Welkin-cf** [comment]
When I received an alert on the rocketchat mobile app, I couldn't see the image and it prompts "No permissions to referred object or it does not exist!", when I remove the {TRIGGER.NAME} in the action, I can see the image normally.

**Comment by vjunior1981** [comment]
After a long, loooong, looooooooong time searching for a fix for the issue 'no graphs on rocketchat', finally I found a solution (at least a workaround).
- **Enable guest user;**
- **Allow guest user to read the required hosts;**
- **Profit :)**

Thanks for this amazing job!

Best regards,
Vitor Jr.

**Comment by estevamdf2** [comment]
> After a long, loooong, looooooooong time searching for a fix for the issue 'no graphs on rocketchat', finally I found a solution (at least a workaround).
> 
> * **Enable guest user;**
> * **Allow guest user to read the required hosts;**
> * **Profit :)**
> 
> Thanks for this amazing job!
> 
> Best regards,
> Vitor Jr.

Great. It's done for me.
